language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
jobs:
  include:
    - stage: test
      script: npm test
    - stage: npm release
      node_js: '10'
      script: mv src/handle-result.js handle-result.js
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
