language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
jobs:
  include:
    - stage: test
      script: npm test
    - stage: npm release
      node_js: '10'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
