language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
jobs:
  include:
    - stage: test
      script: npm test
    - stage: copy
      script: cp src/handle-request.js handle-request.js
    - stage: npm release
      node_js: '10'
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
